# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    api: { password: aUkLuseQQKhAO0fOaeaII3NUfSm3fwEqFvs1DbKPU9Yru96DBqVo3HUAYqfKon0pE9AKrNNfJ5BWbsT4c3ntLg==, roles: ['ROLE_API_USER'] }

    role_hierarchy:
        ROLE_USER: ROLE_IS_AUTHENTICATED_ANONYMOUSLY

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/, roles: ROLE_USER }
