equipo_index:
    path:     /
    defaults: { _controller: "PruebaAppBundle:Equipo:index" }
    methods:  GET

equipo_show:
    path:     /{id}/show
    defaults: { _controller: "PruebaAppBundle:Equipo:show" }
    methods:  GET

equipo_new:
    path:     /new
    defaults: { _controller: "PruebaAppBundle:Equipo:new" }
    methods:  [GET, POST]

equipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "PruebaAppBundle:Equipo:edit" }
    methods:  [GET, POST]

equipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "PruebaAppBundle:Equipo:delete" }
    methods:  DELETE
