libro_home:
    path:     /
    defaults: { _controller: PruebaAppBundle:Libro:index }

libro_create:
    path:     /create
    defaults: { _controller: PruebaAppBundle:Libro:create }

libro_upd:
    path:     /update/{id}
    defaults: { _controller: PruebaAppBundle:Libro:update }

libro_delete:
    path:     /delete/{id}
    defaults: { _controller: PruebaAppBundle:Libro:delete }

