prueba_app_homepage:
    path:     /
    defaults: { _controller: PruebaAppBundle:Default:index }

prueba_app_trabajador:
    resource: "@PruebaAppBundle/Resources/config/trabajador.yml"
    prefix:   /trabajador

prueba_app_contacto:
    resource: "@PruebaAppBundle/Resources/config/contacto.yml"
    prefix:   /contacto

prueba_app_tipocontacto:
    resource: "@PruebaAppBundle/Resources/config/tipocontacto.yml"
    prefix:   /tipocontacto
