services:
#    prueba_app.example:
#        class: Prueba\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# servicio para cargar el fixture AppFixtures en el bundle
    Prueba\AppBundle\DataFixtures\AppFixtures:
        tags: ['doctrine.fixture.orm']
