<?php

namespace Prueba\AppBundle\Repository;

/**
 * EditorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorialRepository extends \Doctrine\ORM\EntityRepository
{
}
